java_test(
    name = "my-redis",
    srcs = ["TestMyRedis.java"],
    test_class = "com.examples.redis.TestMyRedis",
    deps = [
        "//java/com/examples/redis:lib",
        "@junit_junit//jar",
    ],
)
