java_binary(
    name = "main",
    main_class = "com.examples.gson.Main",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_code_gson//jar",
        "@com_google_guava_guava//jar",
    ],
    visibility = ["//visibility:public"],
)
