java_binary(
    name = "main",
    main_class = "com.examples.gson.Main",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_guava_guava",
    ],
    visibility = ["//visibility:public"],
)
