load("@io_bazel_rules_go//go:def.bzl", "go_library")


go_library(
    name = "hi",
    srcs = ["main.go"],
    importpath = "github.com/borg286/better_minig",
    deps = ["@gomodule_redigo//redis:go_default_library"],
)
