{
   "apiVersion":"spinnaker.io/v1alpha2",
   "kind":"SpinnakerService",
   "metadata":{
      "name":"spinnaker"
   },
   "spec":{
      "expose":{
         "service":{
             "type": "NodePort"
         },
         "type":"service"
      },
      "spinnakerConfig":{
         "config":{
            "persistentStorage":{
               "persistentStoreType":"redis",
               "redis":{},
            },
            "version":"1.17.1"
         },
      },
   }
}
